AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

Outputs:

  UsersTable:
    Value: !Ref UsersTable

  BundlesTable:
    Value: !Ref BundlesTable

  ObjectsTable:
    Value: !Ref ObjectsTable

Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-users"
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - KeyType: HASH
        AttributeName: user_id
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UsersScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceId: !Sub "table/${UsersTable}"
        ResourceType: table
        MinReadCapacity: 1
        MaxReadCapacity: 10
        MinWriteCapacity: 1
        MaxWriteCapacity: 10
      TemplateURL: cloudformation-scaling.yaml

  BundlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-bundles"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: close_date
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: user
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: close_date
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  BundlesScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceId: !Sub "table/${BundlesTable}"
        ResourceType: table
        MinReadCapacity: 1
        MaxReadCapacity: 10
        MinWriteCapacity: 1
        MaxWriteCapacity: 10
      TemplateURL: cloudformation-scaling.yaml

  BundlesIndexScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceId: !Sub "table/${BundlesTable}/index/user"
        ResourceType: index
        MinReadCapacity: 1
        MaxReadCapacity: 10
        MinWriteCapacity: 1
        MaxWriteCapacity: 10
      TemplateURL: cloudformation-scaling.yaml

  ObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-objects"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: object_key
        AttributeType: S
      - AttributeName: request_status
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      - AttributeName: object_key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 3
      GlobalSecondaryIndexes:
      - IndexName: request_status
        KeySchema:
        - AttributeName: request_status
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 3

  ObjectsScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceId: !Sub "table/${ObjectsTable}"
        ResourceType: table
        MinReadCapacity: 1
        MaxReadCapacity: 10
        MinWriteCapacity: 3
        MaxWriteCapacity: 50
      TemplateURL: cloudformation-scaling.yaml

  ObjectsIndexScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceId: !Sub "table/${ObjectsTable}/index/request_status"
        ResourceType: index
        MinReadCapacity: 1
        MaxReadCapacity: 10
        MinWriteCapacity: 3
        MaxWriteCapacity: 50
      TemplateURL: cloudformation-scaling.yaml
