AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  Name:
    Type: String

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  Bucket:
    Type: String

  GlacierRequestsTable:
    Type: String

  SenderEmailAddress:
    Type: String

Resources:

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Name}-lambda-dlq"
      MessageRetentionPeriod: 1209600

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${Name}*"
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt DeadLetterQueue.Arn
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          - Effect: Allow
            Action:
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${GlacierRequestsTable}"
          - Effect: Allow
            Action: ses:SendEmail
            Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${SenderEmailAddress}"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Code: src/
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Description: grfn-glacier-restore-notifications $SHA1
      Environment:
        Variables:
          CONFIG_BUCKET: grfn-config
          PROD: glacier-restore-notifications.prod.yaml
          TEST: glacier-restore-notifications.test.yaml
          LATEST: glacier-restore-notifications.test.yaml
      Handler: main.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 20

  LambdaVersion:
    Type: Custom::LambdaVersion
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:406893895021:function:publish-lambda-version:PROD
      FunctionName: !Ref Lambda
      DynamicValueToForceUpdate: "$SHA1"

  TestAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref Lambda
      Name: TEST
      FunctionVersion: !GetAtt LambdaVersion.Version
