version: 0.1


environment_variables:
  plaintext:
    PIPELINE_NAME: "grfn-door"
    IMAGE_NAME: "grfn-door"
    IMAGE_HOST: "765666652335.dkr.ecr.us-west-2.amazonaws.com"
    TASK_DEFINITION_NAME: "grfn-door-dev"
    CLUSTER_NAME: "grfn-door-dev"
    SERVICE_NAME: "grfn-door-dev"


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      - aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME --query "taskDefinition.containerDefinitions" > containerDefinitions.json
      - 'sed -i "s/\(\"image\": .*:\).*\"/\1$(cat sha1.txt)\"/" containerDefinitions.json'
      - aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME --query "taskDefinition.taskRoleArn" --output text > taskRoleArn.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:latest
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_HOST/$IMAGE_NAME:latest
      - docker push $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
      - aws ecs register-task-definition --family $TASK_DEFINITION_NAME --task-role-arn $(cat taskRoleArn.txt) --container-definitions file://containerDefinitions.json
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_DEFINITION_NAME
