version: 0.2

env:
  variables:
    IMAGE_NAME: "door"
    IMAGE_HOST: "406893895021.dkr.ecr.us-east-1.amazonaws.com"
    MATURITY: "PROD"
    SHA1: "cbde6c7"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - sed -i "s/\$SHA1/$SHA1/" cloudformation.yaml
  build:
    commands:
      - docker pull $IMAGE_HOST/$IMAGE_NAME:$SHA1
      - docker tag $IMAGE_HOST/$IMAGE_NAME:$SHA1 $IMAGE_HOST/$IMAGE_NAME:$MATURITY
      - aws cloudformation package --template-file cloudformation.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
  post_build:
    commands:
      - docker push $IMAGE_HOST/$IMAGE_NAME:$MATURITY
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
