version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - python -m pip install -r door/requirements.txt -t door/src/
      - aws cloudformation package --template-file cloudformation.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
