# This build script is designed to run in AWS CodeBuild using the aws/codebuild/docker:17.09.0 image
#   ubuntu 14.04.5
#   docker 17.09.0

version: 0.1

environment_variables:
  plaintext:
    PIPELINE_NAME: "door-test"
    IMAGE_NAME: "door"
    IMAGE_HOST: "406893895021.dkr.ecr.us-east-1.amazonaws.com"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      - sed -i "s/\$SHA1/$(cat sha1.txt)/" Dockerrun.aws.json
  build:
    commands:
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:latest
  post_build:
    commands:
      - docker push $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
      - docker push $IMAGE_HOST/$IMAGE_NAME:latest
artifacts:
  files:
    - Dockerrun.aws.json
