AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  LogBucket:
    Type: String

  DoorContainerImage:
    Description: URL for runtime docker container for door application (repository-url/image:tag)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String

  Hostname:
    Type: String
    
  HelpURL:
    Type: String

  RetentionDays:
    Type: Number
    Default: 7

  AcknowledgementEmailIntervalInMinutes:
    Type: Number
    Default: 720

  CloudFrontKeyPairId:
    Type: String

  PrivateKeySecretName:
    Type: String

Outputs:

  AppUrl:
    Value: !GetAtt DoorStack.Outputs.AppUrl

  LoadBalancerDnsName:
    Value: !GetAtt DoorStack.Outputs.LoadBalancerDnsName

  UrsRedirectUri:
    Value: !GetAtt DoorStack.Outputs.UrsRedirectUri

Resources:

  DynamodbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-db"
      TemplateURL: dynamodb/cloudformation.yaml

  GlacierAvailabilityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-availability"
        BundlesTable: !GetAtt DynamodbStack.Outputs.BundlesTable
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
        EmailQueueName: !GetAtt GlacierNotificationsStack.Outputs.EmailQueueName
        RestoreObjectLambda: !GetAtt GlacierRestoreStack.Outputs.LambdaName
        ObjectStatusLambda: !GetAtt ObjectStatusStack.Outputs.LambdaName
      TemplateURL: glacier-availability/cloudformation.yaml

  GlacierStatusStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-status"
        BundlesTable: !GetAtt DynamodbStack.Outputs.BundlesTable
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-status/cloudformation.yaml

  GlacierUpkeepStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-upkeep"
        BundlesTable: !GetAtt DynamodbStack.Outputs.BundlesTable
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
        EmailQueueName: !GetAtt GlacierNotificationsStack.Outputs.EmailQueueName
        RestoreObjectLambda: !GetAtt GlacierRestoreStack.Outputs.LambdaName
        PollObjectLambda: !GetAtt GlacierPollStack.Outputs.LambdaName
      TemplateURL: glacier-upkeep/cloudformation.yaml

  GlacierRestoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-restore"
        Bucket: !Ref PrivateBucket
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
        RetentionDays: !Ref RetentionDays
        ObjectStatusLambda: !GetAtt ObjectStatusStack.Outputs.LambdaName
      TemplateURL: glacier-restore/cloudformation.yaml

  GlacierPollStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-poll"
        ObjectStatusLambda: !GetAtt ObjectStatusStack.Outputs.LambdaName
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
      TemplateURL: glacier-poll/cloudformation.yaml

  GlacierNotificationsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-notifications"
        UsersTable: !GetAtt DynamodbStack.Outputs.UsersTable
        ObjectsTable: !GetAtt DynamodbStack.Outputs.ObjectsTable
        Hostname: !Ref Hostname
        HelpURL: !Ref HelpURL
        AcknowledgementEmailIntervalInMinutes: !Ref AcknowledgementEmailIntervalInMinutes
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-notifications/cloudformation.yaml

  ObjectStatusStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-object-status"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
      TemplateURL: object-status/cloudformation.yaml

  TemporaryCredentialsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-temporary-credentials"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
      TemplateURL: temporary-credentials/cloudformation.yaml

  DoorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-door"
        LogLevel: !Ref LogLevel
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        CloudFrontDomainName: !GetAtt CloudFrontStack.Outputs.DomainName
        CloudFrontKeyPairId: !Ref CloudFrontKeyPairId
        PrivateKeySecretName: !Ref PrivateKeySecretName
        UsersTable: !GetAtt DynamodbStack.Outputs.UsersTable
        StatusLambda: !GetAtt GlacierStatusStack.Outputs.LambdaName
        ObjectStatusLambda: !GetAtt ObjectStatusStack.Outputs.LambdaName
        AvailabilityLambda: !GetAtt GlacierAvailabilityStack.Outputs.LambdaName
        TemporaryCredentialsLambda: !GetAtt TemporaryCredentialsStack.Outputs.LambdaName
        DoorContainerImage: !Ref DoorContainerImage
        UrsClientId: !Ref UrsClientId
        UrsAuthCode: !Ref UrsAuthCode
        CertificateArn: !Ref CertificateArn
        LoadBalancerCidrIp: !Ref LoadBalancerCidrIp
        Hostname: !Ref Hostname
        HelpURL: !Ref HelpURL
        RetentionDays: !Ref RetentionDays
      TemplateURL: door/cloudformation.yaml

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Ref Name
        Bucket: !Ref PrivateBucket
        LogBucket: !Ref LogBucket
      TemplateURL: cloudfront/cloudformation.yaml

  CloudFrontAclStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-cloudfront-acl"
        Bucket: !Ref PrivateBucket
        CanonicalUserId: !GetAtt CloudFrontStack.Outputs.CanonicalUserId
      TemplateURL: cloudfront-acl/cloudformation.yaml
