AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  UserPreferenceTable:
    Type: String

  DoorContainerRepo:
    Description: URL for docker container repository for door application (repository-url/image)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String
    Default: 0.0.0.0/0

  Hostname:
    Type: String

  Maturity:
    Description: Value for MATURITY tag to be applied to all taggable resources
    Type: String
    Default: DEV
    AllowedValues:
    - DEV
    - TEST
    - PROD

Outputs:

  AppUrl:
    Value: !GetAtt MainStackTest.Outputs.AppUrl

  LoadBalancerDnsName:
    Value: !GetAtt MainStackTest.Outputs.LoadBalancerDnsName

  UrsRedirectUri:
    Value: !GetAtt MainStackTest.Outputs.UrsRedirectUri

Resources:

  MainStackTest:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: MATURITY
        Value: !Ref Maturity
      - Key: APPLICATION
        Value: GRFN-DISTRIBUTION
      Parameters:
        Name: !Ref AWS::StackName
        LogLevel: !Ref LogLevel
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        PrivateBucket: !Ref PrivateBucket
        UserPreferenceTable: !Ref UserPreferenceTable
        DoorContainerImage: !Sub "${DoorContainerRepo}:$SHA1"
        UrsClientId: !Ref UrsClientId
        UrsAuthCode: !Ref UrsAuthCode
        CertificateArn: !Ref CertificateArn
        LoadBalancerCidrIp: !Ref LoadBalancerCidrIp
        Hostname: !Ref Hostname
      TemplateURL: cloudformation-main.yaml
