AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  LogBucket:
    Type: String

  DoorContainerImage:
    Description: URL for runtime docker container for door application (repository-url/image:tag)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String

  Hostname:
    Type: String
    
  CloudFrontKeyPairId:
    Type: String

  PrivateKeySecretName:
    Type: String

Outputs:

  AppUrl:
    Value: !GetAtt DoorStack.Outputs.AppUrl

  LoadBalancerDnsName:
    Value: !GetAtt DoorStack.Outputs.LoadBalancerDnsName

  UrsRedirectUri:
    Value: !GetAtt DoorStack.Outputs.UrsRedirectUri

Resources:

  TemporaryCredentialsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${AWS::StackName}-temporary-credentials"
        Bucket: !Ref PrivateBucket
      TemplateURL: temporary-credentials/cloudformation.yaml

  DoorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${AWS::StackName}-door"
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        CloudFrontDomainName: !GetAtt CloudFrontStack.Outputs.DomainName
        CloudFrontKeyPairId: !Ref CloudFrontKeyPairId
        PrivateKeySecretName: !Ref PrivateKeySecretName
        TemporaryCredentialsLambda: !GetAtt TemporaryCredentialsStack.Outputs.LambdaName
        DoorContainerImage: !Ref DoorContainerImage
        UrsClientId: !Ref UrsClientId
        UrsAuthCode: !Ref UrsAuthCode
        CertificateArn: !Ref CertificateArn
        LoadBalancerCidrIp: !Ref LoadBalancerCidrIp
        Hostname: !Ref Hostname
      TemplateURL: door/cloudformation.yaml

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Ref AWS::StackName
        Bucket: !Ref PrivateBucket
        LogBucket: !Ref LogBucket
      TemplateURL: cloudfront/cloudformation.yaml
