AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  DoorContainerImage:
    Description: URL for runtime docker container for door application (repository-url/image:tag)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String

  Hostname:
    Type: String

  RetentionDays:
    Type: Number
    Default: 7

  AcknowledgementEmailIntervalInMinutes:
    Type: Number
    Default: 720

Outputs:

  AppUrl:
    Value: !GetAtt DoorStack.Outputs.AppUrl

  LoadBalancerDnsName:
    Value: !GetAtt DoorStack.Outputs.LoadBalancerDnsName

  UrsRedirectUri:
    Value: !GetAtt DoorStack.Outputs.UrsRedirectUri

Resources:

  GlacierAvailabilityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-availability"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
        ObjectsTable: !Ref ObjectsTable
        BundlesTable: !Ref BundlesTable
        BundleObjectsTable: !Ref BundleObjectsTable
        EmailQueueName: !GetAtt GlacierNotificationsStack.Outputs.EmailQueueName
      TemplateURL: glacier-availability/cloudformation.yaml

  GlacierStatusStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-status"
        LogLevel: !Ref LogLevel
        ObjectsTable: !Ref ObjectsTable
        BundlesTable: !Ref BundlesTable
        BundleObjectsTable: !Ref BundleObjectsTable
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-status/cloudformation.yaml

  GlacierUpkeepStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-upkeep"
        LogLevel: !Ref LogLevel
        ObjectsTable: !Ref ObjectsTable
        BundlesTable: !Ref BundlesTable
        BundleObjectsTable: !Ref BundleObjectsTable
        EmailQueueName: !GetAtt GlacierNotificationsStack.Outputs.EmailQueueName
        GlacierObjectLambda: !GetAtt GlacierObjectStack.Outputs.LambdaName
      TemplateURL: glacier-upkeep/cloudformation.yaml

  GlacierObjectStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-object"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
        ObjectsTable: !Ref ObjectsTable
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-objects/cloudformation.yaml

  GlacierNotificationsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-notifications"
        LogLevel: !Ref LogLevel
        UsersTable: !Ref UsersTable
        BundleObjectsTable: !Ref BundleObjectsTable
        ObjectsTable: !Ref ObjectsTable
        Hostname: !Ref Hostname
        AcknowledgementEmailIntervalInMinutes: !Ref AcknowledgementEmailIntervalInMinutes
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-notifications/cloudformation.yaml

  DoorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-door"
        LogLevel: !Ref LogLevel
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        PrivateBucket: !Ref PrivateBucket
        UsersTable: !Ref UsersTable
        StatusLambda: !GetAtt GlacierStatusStack.Outputs.LambdaName
        AvailabilityLambda: !GetAtt GlacierAvailabilityStack.Outputs.LambdaName
        DoorContainerImage: !Ref DoorContainerImage
        UrsClientId: !Ref UrsClientId
        UrsAuthCode: !Ref UrsAuthCode
        CertificateArn: !Ref CertificateArn
        LoadBalancerCidrIp: !Ref LoadBalancerCidrIp
        Hostname: !Ref Hostname
        RetentionDays: !Ref RetentionDays
      TemplateURL: door/cloudformation.yaml

  BundlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-bundles"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: close_date
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
      - IndexName: user
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: close_date
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 5

  ObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-objects"
      AttributeDefinitions:
      - AttributeName: object_key
        AttributeType: S
      - AttributeName: availability
        AttributeType: S
      KeySchema:
      - AttributeName: object_key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 40
      GlobalSecondaryIndexes:
      - IndexName: availability
        KeySchema:
        - AttributeName: availability
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  BundleObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-bundle-objects"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: object_key
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      - AttributeName: object_key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 5

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-users"
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - KeyType: HASH
        AttributeName: user_id
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 10
