AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  UserPreferenceTable:
    Type: String

  DoorContainerImage:
    Description: URL for runtime docker container for door application (repository-url/image:tag)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String

  Hostname:
    Type: String

  RetentionDays:
    Type: Number
    Default: 7

Outputs:

  AppUrl:
    Value: !GetAtt DoorStack.Outputs.AppUrl

  LoadBalancerDnsName:
    Value: !GetAtt DoorStack.Outputs.LoadBalancerDnsName

  UrsRedirectUri:
    Value: !GetAtt DoorStack.Outputs.UrsRedirectUri

Resources:

  GlacierAvailabilityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-availability"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
        ObjectsTable: !Ref ObjectsTable
        BundlesTable: !Ref BundlesTable
        BundleObjectsTable: !Ref BundleObjectsTable
      TemplateURL: glacier-availability/cloudformation.yaml


  GlacierStatusStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-status"
        LogLevel: !Ref LogLevel
        ObjectsTable: !Ref ObjectsTable
        BundlesTable: !Ref BundlesTable
        BundleObjectsTable: !Ref BundleObjectsTable
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-status/cloudformation.yaml


  GlacierRequestsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-glacier-requests"
        LogLevel: !Ref LogLevel
        Bucket: !Ref PrivateBucket
        ObjectsTable: !Ref ObjectsTable
        RetentionDays: !Ref RetentionDays
      TemplateURL: glacier-requests/cloudformation.yaml

  DoorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-door"
        LogLevel: !Ref LogLevel
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        PrivateBucket: !Ref PrivateBucket
        UserPreferenceTable: !Ref UserPreferenceTable
        StatusLambda: !GetAtt GlacierStatusStack.Outputs.LambdaName
        AvailabilityLambda: !GetAtt GlacierAvailabilityStack.Outputs.LambdaName
        DoorContainerImage: !Ref DoorContainerImage
        UrsClientId: !Ref UrsClientId
        UrsAuthCode: !Ref UrsAuthCode
        CertificateArn: !Ref CertificateArn
        LoadBalancerCidrIp: !Ref LoadBalancerCidrIp
        Hostname: !Ref Hostname
        RetentionDays: !Ref RetentionDays
      TemplateURL: door/cloudformation.yaml

  BundlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-bundles"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: close_date
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: user
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: close_date
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  ObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-objects"
      AttributeDefinitions:
      - AttributeName: object_key
        AttributeType: S
      - AttributeName: availability
        AttributeType: S
      KeySchema:
      - AttributeName: object_key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: availability
        KeySchema:
        - AttributeName: availability
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  BundleObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-bundle-objects"
      AttributeDefinitions:
      - AttributeName: bundle_id
        AttributeType: S
      - AttributeName: object_key
        AttributeType: S
      KeySchema:
      - AttributeName: bundle_id
        KeyType: HASH
      - AttributeName: object_key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UserPreferencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Name}-user-preferences"
      AttributeDefinitions:
      - AttributeName: user
      AttributeType: S
    KeySchema:
    - KeyType: HASH
      AttributeName: user
    ProvisionedThroughput:
      WriteCapacityUnits: 1
      ReadCapacityUnits: 1
