aws_region: us-east-1
bucket_name: gsfc-ngap-asf-grfn-private-test
expire_time_in_seconds: 15
restore_request_table: glacier-restore-requests-test
user_preference_table: user-preferences-test
glacier_restore_sqs: glacier-restore-requests-test
