AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  Bucket:
    Type: String

  LogBucket:
    Type: String

  LogPrefix:
    Type: String
    Default: cloudfront-access/

Outputs:

  DomainName:
    Value: !GetAtt Distribution.DomainName

  CanonicalUserId:
    Value: !GetAtt OriginAccessIdentity.S3CanonicalUserId

Resources:

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref Name

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Ref Name
        DefaultTTL: 86400
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref Name
        Enabled: True
        PriceClass: PriceClass_100
        Origins:
        - Id: !Ref Bucket
          DomainName: !Sub "${Bucket}.s3.amazonaws.com"
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        DefaultCacheBehavior:
          CachePolicyId: !Ref CachePolicy
          TargetOriginId: !Ref Bucket
          ViewerProtocolPolicy: redirect-to-https
          TrustedSigners:
          - !Ref AWS::AccountId
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations:
            - CU
            - IR
            - KP
            - SY
        Logging:
          Bucket: !Sub "${LogBucket}.s3.amazonaws.com"
          Prefix: !Sub "${LogPrefix}${Name}/"
