aws_region: us-west-2
bucket_name: grfn-d-fe9f1b34-1425-56b9-939f-5f1431a6d1de
expire_time_in_seconds: 15
restore_request_table: grfn-d-glacier-restore-requests
user_preference_table: grfn-d-user-preferences
glacier_retrieval:
  days: 1
  tier: Expedited
glacier_restore_sqs: GRFN-Glacier-Restore-Dev
