AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  CloudFrontDomainName:
    Type: String

  CloudFrontKeyPairId:
    Type: String

  PrivateKeySecretName:
    Type: String

  UsersTable:
    Type: String

  AvailabilityLambda:
    Type: String

  StatusLambda:
    Type: String

  ObjectStatusLambda:
    Type: String

  TemporaryCredentialsLambda:
    Type: String

  DoorContainerImage:
    Description: URL for runtime docker container for door application (repository-url/image:tag)
    Type: String

  UrsClientId:
    Type: String

  UrsAuthCode:
    Type: String

  CertificateArn:
    Type: String

  LoadBalancerCidrIp:
    Type: String

  Hostname:
    Type: String

  HelpURL:
    Type: String

  Ami:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Runtime AMI
    Default: /aws/service/ecs/optimized-ami/amazon-linux/recommended/image_id

  RetentionDays:
    Type: Number
    Default: 7

Outputs:

  AppUrl:
    Value: !Sub "https://${Hostname}/door/"

  LoadBalancerDnsName:
    Value: !GetAtt LoadBalancer.DNSName

  UrsRedirectUri:
    Value: !Sub "https://${Hostname}/door/oauth"

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref Name
      RetentionInDays: 30

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Name}-load-balancer"
      GroupDescription: !Sub "Security group for ${Name} load balancer"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - CidrIp: !Ref LoadBalancerCidrIp
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: !Ref LoadBalancerCidrIp
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref Name
      Subnets: !Ref SubnetId
      SecurityGroups:
      - !GetAtt LoadBalancerSecurityGroup.GroupId

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: redirect
        RedirectConfig:
          StatusCode: HTTP_301
          Protocol: HTTPS
          Port: 443
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: fixed-response
        FixedResponseConfig:
          StatusCode: 503
          ContentType: text/plain
          MessageBody: |-
            Due to the current government shutdown, most data from the Sentinel-1 product lines at ASF will be temporarily unavailable. ASF DAAC may not be able to respond to inquiries until appropriations are enacted. 

            We apologize for the inconvenience this disruption of service may cause to our customers.
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
      - CertificateArn: !Ref CertificateArn
