name: Static code analysis

on: push

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - run: |
          python -m pip install --upgrade pip
          pip install flake8  flake8-import-order flake8-blind-except flake8-builtins

      - run: flake8 --max-line-length=120 --import-order-style=pycharm --statistics --application-import-names door

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: scottbrenner/cfn-lint-action@v2
        with:
          args: "--info --ignore-checks W3002 --template cloudformation.yaml **/cloudformation.yaml"
